# ä¸å¿…ç”¨clash for windows! å•clash.exeå³å¯ï¼ å®šä½é…ç½®ç›®å½•ä¸ºclash.exeæ‰€åœ¨ç›®å½•~åˆ›å»ºå¿«æ·æ–¹å¼ï¼šclash.exe -d "."
# ä¸‹è½½åªåŒ…å«ä¸­å›½IPä¿¡æ¯GEOIPæ–‡ä»¶ï¼šCountry.mmdb ï¼Œä¿å­˜äºä¸Šè¿°ç›®å½•
# port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
# external-controller: 127.0.0.1:9090
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 202.101.226.68
    - 202.101.226.69

  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp

proxies:
  - {name: CA_ga_221, server: 198.57.27.172, port: 5004, type: ss, cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId}
  - {name: CA_ga_388, server: 134.195.196.71, port: 2376, type: ss, cipher: aes-256-gcm, password: faBAoD54k87UJG7}
  - {name: US_XX77, server: 104.16.181.197, port: 443, type: vmess, uuid: 7be43971-52f1-48af-9036-454a94b4723a, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: "/ws/?ed=2048", ws-headers: {Host: download.china666.ml}}
  - {name: US_ga_337, server: 167.88.62.34, port: 7307, type: ss, cipher: aes-256-gcm, password: FoOiGlkAA9yPEGP}
  - {name: YT_Tool3, server: 198.41.221.169, port: 443, type: vmess, uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /sakura/, ws-headers: {Host: zero1.a-yu.xyz}}
proxy-providers:
  subp:
    type: file
    path: proxys.yml
    health-check:
      enable: true
      interval: 1500
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: UQUICK
    type: load-balance
    proxies:
      - YT_Tool3
      - US_XX77
      - US_ga_337
      - CA_ga_221
      - CA_ga_388
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - subp
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: UDOWNLOAD
    type: fallback
    proxies:
      - DIRECT
      - UQUICK
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    proxies:
      - DIRECT
      - UQUICK
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 330
# load-balance url-test fallback
rules:
  - PROCESS-NAME,IDMan.exe,UDOWNLOAD
  - DOMAIN-SUFFIX,bucm.cf,DIRECT
  - DOMAIN-SUFFIX,t.me,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,meiju.pro,DIRECT
  - DOMAIN-SUFFIX,qdm8.com,DIRECT
  - DOMAIN-SUFFIX,hhmm0.com,DIRECT
  - DOMAIN-SUFFIX,bdzybf.com,DIRECT
  - DOMAIN-SUFFIX,wenshibaowenbei.com,DIRECT
  - DOMAIN-SUFFIX,ziyuan605.com,DIRECT
  - DOMAIN-SUFFIX,monidai.com,DIRECT
  - DOMAIN-SUFFIX,fastly.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,w3schools.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,redditmedia.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,redditstatic.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,reddit.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,aiosearch.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ask.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,startpage.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ft.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,facebook.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,twitter.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,twimg.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,wikiwand.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,myspacecdn.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,4shared.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,grossman.io,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,flickr.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitter.im,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ftchinese.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,archive.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,wikipedia.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,dmhy.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,godoc.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,go-zh.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,golang.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.blogger,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.blogspot,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,appspot.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,chrome.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,duckduckgo.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,v2ex.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitlab-static.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitcdn.xyz,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,github,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,git.io,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitbooks.io,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,rawgit.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,13.229.0.0/16,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,20.205.243.0/24,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,23.211.15.99/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,23.246.0.0/18,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,34.210.42.111/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,37.77.184.0/21,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,45.57.0.0/17,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,52.89.124.203/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,54.148.37.5/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,64.120.128.0/17,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,66.197.128.0/17,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,103.5.34.153/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,108.175.32.0/20,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,104.109.129.153/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,110.238.107.47/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,118.26.32.178/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,150.109.28.51/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,192.173.64.0/18,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,198.38.96.0/19,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,198.45.48.0/20,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,203.74.95.131/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,203.74.95.139/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,203.211.4.169/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,203.211.4.193/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,210.201.32.8/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - IP-CIDR,210.201.32.11/32,â™»ï¸ è‡ªåŠ¨é€‰æ‹©,no-resolve
  - DOMAIN-SUFFIX,twitch.tv,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ttvnw.net,UQUICK
  - DOMAIN-SUFFIX,ted.com,UQUICK
  - DOMAIN-SUFFIX,tedcdn.com,UQUICK
  - DOMAIN-SUFFIX,youtube.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gstatic.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ytimg.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,googlevideo.com,UQUICK
  - DOMAIN-SUFFIX,ggpht.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,mtalk.google.com,REJECT
  - DOMAIN-KEYWORD,.google,UQUICK
  - IP-CIDR,1.255.62.0/24,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - IP-CIDR,185.188.32.0/24,DIRECT
  - IP-CIDR,185.188.33.0/24,DIRECT
  - IP-CIDR,185.188.34.0/24,DIRECT
  - IP-CIDR,185.188.35.0/24,DIRECT
  - IP-CIDR6,2a0b:b580::/48,DIRECT
  - IP-CIDR6,2a0b:b581::/48,DIRECT
  - IP-CIDR6,2a0b:b582::/48,DIRECT
  - IP-CIDR6,2a0b:b583::/48,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼