port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: error
external-controller: 127.0.0.1:9090
proxies:[]
proxy-providers:
  subp:
    type: file
    path: proxys.yml
    health-check:
      enable: true
      interval: 9000
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - subp
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å¤–åª’ä½“
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 2
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 3
rules:
  - DOMAIN-KEYWORD,.xn--,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-KEYWORD,.agefans.,DIRECT
  - DOMAIN-SUFFIX,yatu.tv,DIRECT
  - DOMAIN-KEYWORD,.nunuyy.,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,hhmm0.com,DIRECT
  - DOMAIN-SUFFIX,mgtv1.cc,DIRECT
  - DOMAIN-KEYWORD,pianku.,DIRECT
  - DOMAIN-SUFFIX,crxdl.com,DIRECT
  - DOMAIN-SUFFIX,ghproxy.com,DIRECT
  - DOMAIN-SUFFIX,google-fix.com,DIRECT
  - DOMAIN-SUFFIX,sjtu.cf,DIRECT
  - DOMAIN-SUFFIX,shuu.cf,DIRECT
  - DOMAIN-SUFFIX,iwiki.uk,DIRECT
  - DOMAIN-SUFFIX,google.cn,DIRECT
  - DOMAIN-KEYWORD,.google,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,v2ex.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,github,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,cloudfront.net,DIRECT
  - IP-CIDR,13.229.0.0/16,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,20.205.243.0/24,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,23.211.15.99/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,23.246.0.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,34.210.42.111/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,37.77.184.0/21,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,45.57.0.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,52.89.124.203/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,54.148.37.5/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,64.120.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,66.197.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,103.5.34.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,108.175.32.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,104.109.129.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,110.238.107.47/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,118.26.32.178/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,150.109.28.51/32,ğŸŒ å›½å¤–åª’ä½“
  - IP-CIDR,192.173.64.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.38.96.0/19,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.45.48.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.131/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.139/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.169/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.193/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.8/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.11/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ytimg.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ggpht.com,ğŸŒ å›½å¤–åª’ä½“
  - IP-CIDR,1.255.62.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,182.254.116.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.32.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.33.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.34.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.35.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b580::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b581::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b582::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b583::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼