port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies: null
proxy-providers:
  sub_proxy:
    type: file
    path: /proxy-provider.yml
    health-check:
      enable: true
      interval: 3600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - sub_proxy
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å¤–åª’ä½“
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 2
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 3
rules:
  - DOMAIN-SUFFIX,shuu.cf,DIRECT
  - DOMAIN-KEYWORD,pianku.,DIRECT
  - DOMAIN-SUFFIX,v2ex.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.nunuyy.,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.haitu,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,github,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,google.cn,DIRECT
  - DOMAIN-KEYWORD,.google,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,jtvnw.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ttvnw.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,twitch.tv,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,twitchcdn.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,deezer.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dzcdn.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,joox.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,jooxweb-api,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,.kkbox.,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,kfs.io,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pandora.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,p-cdn.us,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,sndcdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,soundcloud.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pscdn.co,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,scdn.co,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,spoti.fi,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,spotify.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,-spotify-com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tidal.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,himalaya.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,overcast.fm,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,abema.io,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,abema.tv,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ameba.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hayabusa.io,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,c4assets.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,channel4.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,aiv-cdn.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,aiv-delivery.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,amazonvideo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,primevideo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,images-amazon.com,ğŸŒ å›½å†…åª’ä½“
  - DOMAIN-SUFFIX,amazon.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,akamaihd.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,cloudfront.net,DIRECT
  - DOMAIN-KEYWORD,avoddashs,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,.apple.,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,bahamut.com.tw,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,gamer.com.tw,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hinet.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,bbc.co.uk,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,bbci.co.uk,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,bbcfmt,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,uk-live,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,biliintl.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,apm-misaka.biliapi.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,p.bstarstatic.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dazn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dazn-api.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dazndn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,indazn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,voddazn,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,disco-api.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,discoveryplus.,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dnitv.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,bamgrid.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,disneyplus.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,disney-plus.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,disneystreaming.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dssott.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,cdn.registerdisney.go.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dmm.co.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dmm.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dmm-extension.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,encoretvb.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,edge.api.brightcove.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hbo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hbogo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hbonow.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hbomax.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hbomaxcdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,.hbogoasia.,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,hbolb.onwardsmg.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,hbounify-prod.evergent.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,players.brightcove.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ocnttv.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hulu.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,huluim.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hulustream.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,happyon.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hjholdings.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,hulu.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,itv.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,itvstatic.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,iq.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,intl.iqiyi.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,intl-rcd.iqiyi.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,intl-subscription.iqiyi.com,ğŸŒ å›½å¤–åª’ä½“
  - IP-CIDR,13.229.0.0/16,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,20.205.243.0/24,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,23.211.15.99/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,23.246.0.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,34.210.42.111/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,37.77.184.0/21,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,45.57.0.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,52.89.124.203/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,54.148.37.5/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,64.120.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,66.197.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,103.5.34.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,108.175.32.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,104.109.129.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,110.238.107.47/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,118.26.32.178/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,150.109.28.51/32,ğŸŒ å›½å¤–åª’ä½“
  - IP-CIDR,192.173.64.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.38.96.0/19,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.45.48.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.131/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.139/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.169/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.193/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.8/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.11/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - DOMAIN,kktv-theater.kk.stream,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,naver.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,smartmediarep.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,netflix.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,dualstack.,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,dmc.nico,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,nicovideo.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,nimg.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,nowe.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,nowestatic.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,cbsi.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,cbsaavideo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,cbsivideo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,paramountplus.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pplusstatic.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,cbsi.live.ott.irdeto.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,syncbak.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,link.theplatform.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pbs.org,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,phncdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,phprcdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pornhub.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,pornhubpremium.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,skyking.com.tw,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,hamifans.emome.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,byteoversea.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ibytedtos.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,muscdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,musical.ly,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tiktok.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tik-tokapi.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tiktokcdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tiktokv.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-KEYWORD,-tiktokcdn-com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,tver.jp,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,edge.api.brightcove.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,wetv.vip,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,wetvinfo.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ytimg.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ggpht.com,ğŸŒ å›½å¤–åª’ä½“
  - IP-CIDR,1.255.62.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,182.254.116.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.32.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.33.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.34.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.35.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b580::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b581::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b582::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b583::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
