port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: error
external-controller: 127.0.0.1:9090
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8

  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record

  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114 # default value
    - 8.8.8.8 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp

proxies:
  - name: "ss1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
proxy-providers:
  provider1:
    type: http
    url: https://ghproxy.com/https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/clash/clash.provider.yaml
    interval: 800
    path: provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  subp:
    type: file
    path: proxys.yml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxy-groups:
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: load-balance
    use:
      - subp
      - provider1
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å¤–åª’ä½“
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 500
  - name: ğŸŒ å›½å†…åª’ä½“
    type: url-test
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 2
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    proxies:
      - DIRECT
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 400
    _index: 3
rules:
  - DOMAIN-KEYWORD,.haitu,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,t.me,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,olevod.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,akamaihd.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,vidoevo.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,redditmedia.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,redditstatic.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,reddit.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,aiosearch.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ask.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,startpage.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ft.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,verycd.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,aiosearch.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,facebook.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,twitter.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,twimg.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,airbnb.io,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,wikiwand.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,myspacecdn.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,4shared.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,grossman.io,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,flickr.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitter.im,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,nytimes.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ftchinese.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,archive.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,wikipedia.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,dmhy.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,godoc.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,go-zh.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,golang.org,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.blogger.,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,.blogspot.,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,appspot.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,chrome.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,duckduckgo.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,v2ex.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitlab-static.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitcdn.xyz,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-KEYWORD,github,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,13.229.0.0/16,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,20.205.243.0/24,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,23.211.15.99/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,23.246.0.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,34.210.42.111/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,37.77.184.0/21,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,45.57.0.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,52.89.124.203/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,54.148.37.5/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,64.120.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,66.197.128.0/17,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,103.5.34.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,108.175.32.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,104.109.129.153/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,110.238.107.47/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,118.26.32.178/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,150.109.28.51/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,192.173.64.0/18,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.38.96.0/19,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,198.45.48.0/20,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.131/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.74.95.139/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.169/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,203.211.4.193/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.8/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - IP-CIDR,210.201.32.11/32,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - DOMAIN-SUFFIX,twitch.tv,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ttvnw.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ted.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,tedcdn.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,gstatic.cn,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,gstatic.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ytimg.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,ggpht.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,.google,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,1.255.62.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,182.254.116.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.32.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.33.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.34.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR,185.188.35.0/24,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b580::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b581::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b582::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - IP-CIDR6,2a0b:b583::/48,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼